### ISSUE TITLE
export command can do what tape_bulk_eject does

### ISSUE THREAD

**Issue by pstorz** [Robpol86/tape_bulk_eject#1]
Hello Rob,
I just found your tape_bulk_eject script.

fyi: you do not  need to do that yourself, as the "export" command in bareos does exactly what your script does.

See: 

http://doc.bareos.org/master/html/bareos-manual-main-reference.html#x1-175058

best regards,

Philipp

**Comment by Robpol86** [comment]
Hmm interesting, I'll have to check it out.

**Comment by Robpol86** [comment]
I looked into it a bit more and unfortunately my PV-124T doesn't have an export slot. So I get:

```
*export volume=000004L3|000040L3|000017L3
Automatically selected Storage: Tape
Connecting to Storage daemon Tape at moops.rob86.net:9103 ...
3306 Issuing autochanger "slots" command.
Device "PV-124T" has 16 slots.
Connecting to Storage daemon Tape at moops.rob86.net:9103 ...
3306 Issuing autochanger "listall" command.
Not enough free export slots available to export 3 volumes
*
```

http://en.community.dell.com/support-forums/storage/f/1216/t/19321411

Thanks anyways, maybe when my autoloader dies I'll keep this in mind and purchase a replacement with export slots.
